document.write("<table width=\"850\" border=\"0\" height=\"184\">");
document.write("<tbody>");
document.write("<tr>");
document.write("<td> <img src=\"Images/zhanghao.png\" alt=\"Hao Zhang\"");
document.write("width=\"350\" height=\"250\"> <\/td>");
document.write("<td>");
document.write("<h1>Hao Zhang 张浩</h1>");
document.write("<br>");
document.write("<br>");
      
document.write("<br>");
document.write("<br>");
document.write("<b>Contact info:</b><br>");
document.write(" Chengdu, Sichuan, China. <br>");
document.write("E-mail: aaronzhangfy@163.com, Wechat: 156811991O1<br>");
document.write("<br>");
document.write("&nbsp;");
document.write("<a href=\"https://www.researchgate.net/profile/Hao-Zhang-589\"><img src=\"Images\/Researchgate.jpg\" alt=\"Researchgate\" width=\"25\" border=\"0\" height=\"25\"> <\/a> &nbsp;");
document.write("<a href=\"https:\/\/github.com\/haozhangSWJTU\"><img src=\"Images\/GitHub-Mark-120px-plus.png\" alt=\"GitHub\" width=\"25\" border=\"0\" height=\"25\"> <\/a> &nbsp;");
document.write("<\/td>");
document.write("<\/tr>");
document.write("<\/tbody>");
document.write("<\/table>");
document.write("<br>");
document.write("<br>");
